### PR TITLE
Upstream Updates

### PR DESCRIPTION
**Pull request by Grumbel**
I removed .appdata and .desktop as they are now  provided by upstream. Pingus moved from GitHub to GitLab, so those URLs are updated as well.

I also adjusted the app-id from "org.seul.pingus" to "org.seul.pingus.Pingus", as org.seul.pingus is really just the domain part, not the app name. So I guess the repository itself will need renaming as well.

If somebody could grant me write permissions for the repository that would be splendid. I am the upstream maintainer of Pingus.

### CODE REVIEW

**Comment by Alexander-Wilms** [comment]
This repo would need to be renamed as well.

**Comment by barthalion** [comment]
Renaming requires help from someone with ssh access to servers hosting the repo. Would be nice to proceed with the old name for now (and maybe open issue for the rename in flathub/flathub).

**Comment by barthalion** [comment]
@Grumbel, I've added you to collaborators, make sure to accept the invitation to get write access.

**Comment by Grumbel** [comment]
Ok, changed the app-id back for the moment and commited the rest.

**Pull request merged**
