### PR TITLE
Update runtime

### PR DESCRIPTION
**Pull request by JakobDev**

### CODE REVIEW

**Comment by Newbytee** [comment]
Do you plan to fix this?

**Comment by JakobDev** [comment]
I can take a look at it

**Comment by JakobDev** [comment]
@Newbytee Looks like the App [has been marked as EOL last month](https://github.com/flathub/org.seul.pingus/commit/810efc34a15ccd5d7332500a6c493e440ad35dc9)

**Comment by Newbytee** [comment]
Yeah, I will un-EOL it.

**Comment by Newbytee** [comment]
I'll deal with the shared-modules fork Grumbel had being removed in https://github.com/flathub/org.seul.pingus/pull/10. I'll let you know when I've fixed that, then we can look into merging this.

**Comment by JakobDev** [comment]
> I'll deal with the shared-modules fork 

I'm already working on it

**Comment by Newbytee** [comment]
Thanks!

**Comment by JakobDev** [comment]
Can I replace the JSON with YAML?

**Comment by Newbytee** [comment]
I would prefer to keep it JSON. Why?

**Comment by JakobDev** [comment]
I personal like the Synatx of YAML more, but if you prefer to keep JSON, I can do that.

But we have a big problem: Pingus contains https://github.com/Grumbel/strutcpp as submodule. This repo itself contains https://gitlab.com/grumbel/tinycmmc as submodule. But https://gitlab.com/grumbel/tinycmmc no longer exists, meaning I can't clone the Pingus repo. I had [opened a Issue](https://github.com/Grumbel/strutcpp/issues/1). There are also no up to date tarballs which contains the full source, so until this is fixed, we can't build Pingus.

**Comment by Newbytee** [comment]
https://github.com/grumbel/tinycmmc still exists.

**Comment by JakobDev** [comment]
I know, but I don't know a way to tell this git during cloning.

**Comment by Newbytee** [comment]
Oh, I see then. One approach could be to disable recursive submodule cloning and manually clone the submodules. However, I'm not sure what the best way to accomplish this with `flatpak-builder` would be.

**Comment by JakobDev** [comment]
It is possible to do a git clone in a sub directory, but Pingus has many submodules which itself also have submodules, so this would be a loot of work. I think it's better to just wait until this is fixed.

**Comment by JakobDev** [comment]
I try now to write a script for the submdoules

**Comment by JakobDev** [comment]
I have included all submodules in the Manifest, but now I get this error:
```
-- Package geom not found, trying external/geom
CMake Error at external/tinycmmc/modules/tinycmmc/FindDependency.cmake:27 (message):
  The git submodule "external/geom" could not be found.  To retrieve it, run:

      git submodule update --init --recursive

Call Stack (most recent call first):
  CMakeLists.txt:68 (tinycmmc_find_dependency)
  CMakeLists.txt:79 (build_dependencies)
```
The [tinymmc repo](https://github.com/grumbel/tinycmmc) don't have any submodules.

I will upload my source, but  think we should just keep it EOL, given how broken it is.

**Comment by AsciiWolf** [comment]
Replaced by #11.

**Pull request closed without merging**
