### PR TITLE
Update runtime to 22.08

### PR DESCRIPTION
**Pull request by bbhtt**

### CODE REVIEW

**Comment by bbhtt** [comment]
Hrm, none of the shared module manifests exists upstream, not sure why they are part of the submodule...

**Comment by bbhtt** [comment]
```
FAILED: CMakeFiles/libpingus.dir/src/editor/level_properties.cpp.o 
/usr/bin/c++ -DFMT_LOCALE -DFMT_SHARED -DPROJECT_NAME=\"pingus\" -DPROJECT_VERSION=\"0.7.6-543-g25d7f3ffb\" -DTINYGETTEXT_WITH_SDL -I/run/build/pingus/src -I/run/build/pingus/external/argparser/include -I/run/build/pingus/external/argparser/src -I/run/build/pingus/external/geomcpp/include -I/run/build/pingus/external/logmich/include -I/run/build/pingus/external/priocpp/include -I/run/build/pingus/external/tinygettext/include -I/run/build/pingus/external/strutcpp/include -I/run/build/pingus/external/xdgcpp/include -I/run/build/pingus/external/wstsound/include -isystem /app/lib -isystem /run/build/pingus/external/priocpp/external/sexp-cpp/include -isystem /usr/include/x86_64-linux-gnu/SDL2 -isystem /usr/include/SDL2 -isystem /usr/include/AL -isystem /usr/include/opus -isystem /usr/include/libpng16 -isystem /app/include/sigc++-2.0 -isystem /app/lib/sigc++-2.0/include -O2 -pipe -g -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -O3 -DNDEBUG -std=c++20 -D_REENTRANT -MD -MT CMakeFiles/libpingus.dir/src/editor/level_properties.cpp.o -MF CMakeFiles/libpingus.dir/src/editor/level_properties.cpp.o.d -o CMakeFiles/libpingus.dir/src/editor/level_properties.cpp.o -c /run/build/pingus/src/editor/level_properties.cpp
/run/build/pingus/src/editor/level_properties.cpp: In constructor ‘Editor::LevelProperties::LevelProperties(Editor::EditorScreen*, const Rect&)’:
/run/build/pingus/src/editor/level_properties.cpp:84:34: error: ‘bind’ is not a member of ‘std’
```

**Comment by bbhtt** [comment]
Above error was fixed But then

one of the submodule is failing to build:

```
/run/build/pingus/external/strutcpp/include/strut/split.hpp:25:6: error: ‘vector’ in namespace ‘std’ does not name a template type
   25 | std::vector<std::string> split(std::string_view text, char delimiter)
      |      ^~~~~~
/run/build/pingus/external/strutcpp/include/strut/split.hpp:1:1: note: ‘std::vector’ is defined in header ‘<vector>’; did you forget to ‘#include <vector>’?
  +++ |+#include <vector>
    1 | // strut - Collection of string utilities
[32/269] Building CXX object CMakeFiles/libpingus.dir/src/engine/display/null_framebuffer.cpp.o
```

Looks like this is fixed upstream, but I cannot bump the commit as some dependencies like tinycmmc is missing. cc @Grumbel

**Comment by hfiguiere** [comment]
> Can't manipulate the submodule as it is part of the project repo.

you can always patch submodules.

**Comment by bbhtt** [comment]
> > Can't manipulate the submodule as it is part of the project repo.
> 
> you can always patch submodules.

Disheartening to see them getting insta-EOL-ed... oh well

**Comment by bbhtt** [comment]
Oh this was already EOL-ed https://github.com/flathub/org.seul.pingus/commit/84d91eee464c7c779a50395f5e997ad03e020481 ... 🙃

**Comment by hfiguiere** [comment]
we could un-EOL this.

**Pull request closed without merging**
